deye_cloud:
  app_id: YOUR_APP_ID
  app_secret: YOUR_APP_SECRET
  email: YOUR_EMAIL
  password: YOUR_PASSWORD
  device_sn: YOUR_DEVICE_SERIAL_NUMBER
  base_url: https://eu1-developer.deyecloud.com/v1.0
